CesiCompanyDirectory/Models/Service.cs
using Microsoft.AspNetCore.Mvc;

namespace CesiCompanyDirectory.Models;

[BindProperties]
public class Service
{
    public int Id { get; set; }
    public string Name { get; set; }

    // Navigation properties
    public ICollection<Employee> Employees { get; set; }
}

CesiCompanyDirectory/Models/Site.cs
using Microsoft.AspNetCore.Mvc;

namespace CesiCompanyDirectory.Models;

[BindProperties]
public class Site
{
    public int Id { get; set; }
    public string City { get; set; }
    public string Name { get; set; }

    // Navigation properties
    public ICollection<Employee> Employees { get; set; }
}

CesiCompanyDirectory/Pages/AddNewEmployee.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class AddNewEmployee : PageModel
{
    
    private readonly IEmployeeService _employeeService;
    private readonly ISiteService _siteService;
    private readonly IServiceService _serviceService;

    public ICollection<Site> AllSites;
    public ICollection<Service> AllServices;

    public AddNewEmployee(IEmployeeService employeeService, ISiteService siteService, IServiceService serviceService)
    {
        _employeeService = employeeService;
        _siteService = siteService;
        _serviceService = serviceService;
        AllServices = _serviceService.GetServicesAsync().Result;
        AllSites = _siteService.GetSitesAsync().Result;
    }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAddEmployee([FromForm] Employee employee)
    {
        var employeeToAdd = new Employee
        {
            FirstName = employee.FirstName,
            LastName = employee.LastName,
            PhoneNumber = employee.PhoneNumber,
            MobileNumber = employee.MobileNumber,
            Email = employee.Email,
            SiteId = employee.SiteId,
            ServiceId = employee.ServiceId
        };

        await _employeeService.AddEmployeeAsync(employeeToAdd);
        
        var addedEmployee = await _employeeService.GetEmployeeByIdAsync(employeeToAdd.Id);

        return RedirectToPage("./EmployeeDetails", new { employeeId = addedEmployee.Id });
    }
}

CesiCompanyDirectory/Pages/AddService.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class AddService : PageModel
{
    
    private readonly IServiceService _serviceService;

    public AddService(IServiceService serviceService)
    {
        _serviceService = serviceService;
    }

    public void OnGet()
    {
        
    }
    
    public async Task<IActionResult> OnPostAddService([FromForm] Service service)
    {
        var serviceToAdd = new Service
        {
            Name = service.Name
        };

        await _serviceService.CreateServiceAsync(serviceToAdd);

        return RedirectToPage("/Services");
    }
}

CesiCompanyDirectory/Pages/AddSite.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class AddSite : PageModel
{
    private readonly ISiteService _siteService;

    public AddSite(ISiteService siteService)
    {
        _siteService = siteService;
    }

    public void OnGet()
    {
        
    }
    
    public async Task<IActionResult> OnPostAddSite([FromForm] Site site)
    {
        var siteToAdd = new Site
        {
            Name = site.Name,
            City = site.City
        };

        await _siteService.CreateSiteAsync(siteToAdd);
        
        return RedirectToPage("/Sites");
    }
}

CesiCompanyDirectory/Pages/EmployeeDetails.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class EmployeeDetails : PageModel
{
    private readonly IEmployeeService _employeeService;
    private readonly ISiteService _siteService;
    private readonly IServiceService _serviceService;
    
    
    public Employee Employee;
    public Site? Site;
    public Service? Service;
    public ICollection<Site> AllSites;
    public ICollection<Service> AllServices;

    
    public EmployeeDetails(IServiceService serviceService, ISiteService siteService, IEmployeeService employeeService)
    {
        _serviceService = serviceService;
        _siteService = siteService;
        _employeeService = employeeService;
    }

    public async Task OnGet(int employeeId)
    {
        if (employeeId != null)
        {
            Employee = await _employeeService.GetEmployeeByIdAsync(employeeId);
            if (Employee.Site is not null)
            {
                Site = await _siteService.GetSiteByIdAsync((int) Employee.SiteId);
            }
            else
            {
                Site = new Site();
            }
            
            if (Employee.Service is not null)
            {
                Service = await _serviceService.GetServiceByIdAsync((int) Employee.ServiceId);
            }
            else
            {
                Service = new Service();
            }
        }
    
        AllSites = await _siteService.GetSitesAsync();
        AllServices = await _serviceService.GetServicesAsync();
    }
    
    public async Task<IActionResult> OnPostUpdateEmployee(int employeeId, [FromForm] Employee employee)
    {
        var employeeInput = new Employee
        {
            Id = employeeId,
            FirstName = employee.FirstName,
            LastName = employee.LastName,
            PhoneNumber = employee.PhoneNumber,
            MobileNumber = employee.MobileNumber,
            Email = employee.Email,
        };

        if (employee.ServiceId != null)
        {
            employeeInput.Service =  await _serviceService.GetServiceByIdAsync((int)employee.ServiceId);
        }
    
        if (employee.SiteId != null)
        {
            employeeInput.Site =  await _siteService.GetSiteByIdAsync((int)employee.SiteId);
        }
        
        Employee = await _employeeService.GetEmployeeByIdAsync(employeeId);
        if (Employee != null)
        {
            Employee.FirstName = employeeInput.FirstName;
            Employee.LastName = employeeInput.LastName;
            Employee.PhoneNumber = employeeInput.PhoneNumber;
            Employee.MobileNumber = employeeInput.MobileNumber;
            Employee.Email = employeeInput.Email;
            Employee.Service = employeeInput.Service;
            Employee.Site = employeeInput.Site;
            Employee.Picture = employeeInput.Picture;
            await _employeeService.UpdateEmployeeAsync(Employee);
        }
       
        
        return RedirectToPage("./EmployeeDetails", new {employeeId = Employee.Id });
    }

    public async Task<IActionResult> OnPostDeleteEmployee(int employeeId)
    {
        await _employeeService.DeleteEmployeeAsync(employeeId);

        return RedirectToPage("./Index");
    }
}

CesiCompanyDirectory/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CesiCompanyDirectory/Pages/Index.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IEmployeeService _employeeService;
    private readonly IServiceService _serviceService;
    private readonly ISiteService _siteService;

    // Add these properties
    [BindProperty(SupportsGet = true)]
    public string NameSearchTerm { get; set; }
    
    [BindProperty(SupportsGet = true)]
    public string SiteSearchTerm { get; set; }
    
    [BindProperty(SupportsGet = true)]
    public string ServiceSearchTerm { get; set; }
    public IList<Employee> Employees { get; set; }
    
    public List<Site> Sites { get; set; }
    public List<Service> Services { get; set; }


    public IndexModel(ILogger<IndexModel> logger, IEmployeeService employeeService, ISiteService siteService, IServiceService serviceService)
    {
        _logger = logger;
        _employeeService = employeeService;
        _siteService = siteService;
        _serviceService = serviceService;
    }

    public async Task OnGet()
    {
        if (!string.IsNullOrEmpty(NameSearchTerm))
        {
            Employees = await _employeeService.SearchByNameAsync(NameSearchTerm);
        }
        else if (!string.IsNullOrEmpty(SiteSearchTerm))
        {
            Employees = await _employeeService.SearchBySiteAsync(SiteSearchTerm);
        }
        else if (!string.IsNullOrEmpty(ServiceSearchTerm))
        {
            Employees = await _employeeService.SearchByServiceAsync(ServiceSearchTerm);
        }
        else
        {
            Employees = await _employeeService.GetAllEmployeesAsync();
        }
        
        Sites = await _siteService.GetSitesAsync();
        Services = await _serviceService.GetServicesAsync();
    }
}

CesiCompanyDirectory/Pages/Services.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class Services : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IServiceService _serviceService;

    public IList<Service> AllService { get; set; }

    public Services(ILogger<IndexModel> logger, IServiceService serviceService)
    {
        _logger = logger;
        _serviceService = serviceService;
    }

    public async Task OnGet()
    {
        AllService = await _serviceService.GetServicesAsync();
    }
}

CesiCompanyDirectory/Pages/Sites.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class Sites : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly ISiteService _siteService;

    public IList<Site> AllSite { get; set; }

    public Sites(ILogger<IndexModel> logger, ISiteService siteService)
    {
        _logger = logger;
        _siteService = siteService;
    }

    public async Task OnGet()
    {
        AllSite = await _siteService.GetSitesAsync();
    }
}

CesiCompanyDirectory/Pages/UpdateDeleteService.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class UpdateDeleteService : PageModel
{
    private readonly IServiceService _serviceService;

    public Service? Service;

    public UpdateDeleteService(IServiceService serviceService)
    {
        _serviceService = serviceService;
    }

    public async Task OnGet(int serviceId)
    {
        Service = await _serviceService.GetServiceByIdAsync(serviceId);
    }

    /// <summary>
    /// Handles updating a service with the specified ID.
    /// </summary>
    /// <param name="serviceId">The ID of the service to update.</param>
    /// <param name="service">The updated service object.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    public async Task<IActionResult> OnPostUpdateService(int serviceId, [FromForm] Service service)
    {
        var serviceInput = new Service
        {
            Id = serviceId,
            Name = service.Name,
        };

        Service = await _serviceService.GetServiceByIdAsync(serviceId);
        if (Service != null)
        {
            // Update the service with the new data
            Service.Name = serviceInput.Name;
            await _serviceService.UpdateServiceAsync(Service);
        }

        // Redirect back to the services page
        return RedirectToPage("./Services");
    }

    /// <summary>
    /// Handles deleting a service with the specified ID.
    /// </summary>
    /// <param name="serviceId">The ID of the service to delete.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    public async Task<IActionResult> OnPostDeleteService(int serviceId)
    {
        // Check if there are any employees linked to the service
        bool serviceDeleted = await _serviceService.DeleteServiceAsync(serviceId);

        if (serviceDeleted)
        {
            // Service was deleted, redirect to page
            return RedirectToPage("./Services");
        }

        // Service was not deleted, display an error message
        TempData["ErrorMessage"] = "Cannot delete service - employees are linked to it.";
        return Page();
    }

}

CesiCompanyDirectory/Pages/UpdateDeleteSite.cshtml.cs
using CesiCompanyDirectory.Models;
using CesiCompanyDirectory.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CesiCompanyDirectory.Pages;

public class UpdateDeleteSite : PageModel
{
    private readonly ISiteService _siteService;

    public Site? Site;

    public UpdateDeleteSite(ISiteService siteService)
    {
        _siteService = siteService;
    }

    public async Task OnGet(int siteId)
    {
        Site = await _siteService.GetSiteByIdAsync(siteId);
    }
    
    /// <summary>
    /// Updates the site with the specified ID with the provided data.
    /// </summary>
    /// <param name="siteId">The ID of the site to update.</param>
    /// <param name="site">The updated data for the site.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    public async Task<IActionResult> OnPostUpdateSite(int siteId, [FromForm] Site site)
    {
        var siteInput = new Site
        {
            Id = siteId,
            Name = site.Name,
            City = site.City
        };

        // Get the existing site data from the database
        Site = await _siteService.GetSiteByIdAsync(siteId);

        // Update the site if it exists
        if (Site != null)
        {
            Site.Name = siteInput.Name;
            Site.City = siteInput.City;
            await _siteService.UpdateSiteAsync(Site);
        }

        return RedirectToPage("./Sites");
    }

    /// <summary>
    /// Deletes the site with the specified ID if it is empty (i.e., has no employees linked to it).
    /// Otherwise, sets an error message in TempData and redirects to the Sites page.
    /// </summary>
    /// <param name="siteId">The ID of the site to delete.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    public async Task<IActionResult> OnPostDeleteSite(int siteId)
    {
        // Check if the site has any employees linked to it
        bool isSiteEmpty = await _siteService.IsSiteEmptyAsync(siteId);

        // If the site is not empty, set an error message and redirect to the Sites page
        if (!isSiteEmpty)
        {
            TempData["ErrorMessage"] = "Cannot delete site because it has employees linked to it.";
            return RedirectToPage("./Sites");
        }

        // Otherwise, delete the site
        await _siteService.DeleteSiteAsync(siteId);

        return RedirectToPage("./Sites");
    }

}

CesiCompanyDirectory/Pages/AddNewEmployee.cshtml
@page
@model CesiCompanyDirectory.Pages.AddNewEmployee

@{
    ViewData["Title"] = "Add Employee";
}


@if (User.IsInRole("Admin"))
{
    <div class="container">
        <div class="row d-flex justify-content-between align-items-center mb-4">
            <dl class="col-md-9">
                <h1>Employee Details</h1>
                <dl class="row">
                    <form method="post">
                        <dt class="col-sm-3">Picture</dt>
                        <dd class="col-sm-9">
                            <img src="/user.png" class="img-fluid" alt="Employee Picture">
                        </dd>
                        <dt class="col-sm-3">First Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="FirstName" maxlength="255" class="form-control">
                        </dd>
                        <dt class="col-sm-3">Last Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="LastName" maxlength="255" class="form-control">
                        </dd>
                        <dt class="col-sm-3">Phone Number</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="PhoneNumber" maxlength="15" class="form-control">
                        </dd>
                        <dt class="col-sm-3">Mobile Number</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="MobileNumber" maxlength="15" class="form-control">
                        </dd>
                        <dt class="col-sm-3">Email</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="Email" maxlength="255" class="form-control">
                        </dd>
                        <dt class="col-sm-3">Service</dt>
                        <dd class="col-sm-9">
                            <select class="form-control" name="ServiceId">
                                @foreach (var service in Model.AllServices)
                                {
                                    <option value="@service.Id">@service.Name</option>
                                }
                            </select>
                        </dd>
                        <dt class="col-sm-3">Site</dt>
                        <dd class="col-sm-9">
                            <select class="form-control" name="SiteId">
                                @foreach (var site in Model.AllSites)
                                {
                                    <option value="@site.Id">@site.Name</option>
                                }
                            </select>
                        </dd>
                        <div class="d-flex justify-content-end mb-4">
                            <button asp-page-handler="AddEmployee" class="btn btn-primary" type="submit">Add Employee</button>
                        </div>
                    </form>
                </dl>
            </dl>
        </div>
    </div>
}

CesiCompanyDirectory/Pages/AddService.cshtml
@page
@model CesiCompanyDirectory.Pages.AddService

@{
    ViewData["Title"] = "Add Service";
}


@if (User.IsInRole("Admin"))
{
    <div class="container">
        <div class="row d-flex justify-content-between align-items-center mb-4">
            <dl class="col-md-9">
                <h1>Service to add</h1>
                <dl class="row">
                    <form method="post">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="Name" maxlength="255" class="form-control">
                        </dd>
                        <div class="d-flex justify-content-end mb-4">
                            <button asp-page-handler="AddService" class="btn btn-primary" type="submit">Add Service</button>
                        </div>
                    </form>
                </dl>
            </dl>
        </div>
    </div>
}

CesiCompanyDirectory/Pages/AddSite.cshtml
@page
@model CesiCompanyDirectory.Pages.AddSite

@{
    ViewData["Title"] = "Add Site";
}


@if (User.IsInRole("Admin"))
{
    <div class="container">
        <div class="row d-flex justify-content-between align-items-center mb-4">
            <dl class="col-md-9">
                <h1>Site to add</h1>
                <dl class="row">
                    <form method="post">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="Name" maxlength="255" class="form-control">
                        </dd>
                         <dt class="col-sm-3">City</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="City" maxlength="255" class="form-control">
                        </dd>
                        <div class="d-flex justify-content-end mb-4">
                            <button asp-page-handler="AddSite" class="btn btn-primary" type="submit">Add Site</button>
                        </div>
                    </form>
                </dl>
            </dl>
        </div>
    </div>
}

CesiCompanyDirectory/Pages/EmployeeDetails.cshtml
@page
@model CesiCompanyDirectory.Pages.EmployeeDetails

@{
    ViewData["Title"] = "Employee Details";
}

<div class="container">
    <div class="row d-flex justify-content-between align-items-center mb-4">
        <dl class="col-md-9">
            <h1>Employee Details</h1>
            <dl class="row">
                <form method="post">
                    <dt class="col-sm-3">Picture</dt>
                    <dd class="col-sm-9">
                        @if (!string.IsNullOrEmpty(Model.Employee.Picture))
                        {
                            <img src="@Model.Employee.Picture" class="img-fluid" alt="Employee Picture">
                        }
                        else
                        {
                            <img src="/user.png" class="img-fluid" alt="Employee Picture">
                        }
                    </dd>
                    <dt class="col-sm-3">First Name</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <input type="text" name="FirstName" maxlength="255" value="@Model.Employee.FirstName" class="form-control">
                        }
                        else
                        {
                            @Model.Employee.FirstName
                        }
                    </dd>
                    <dt class="col-sm-3">Last Name</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <input type="text" name="LastName" class="form-control" maxlength="255" value="@Model.Employee.LastName">
                        }
                        else
                        {
                            @Model.Employee.LastName
                        }
                    </dd>
                    <dt class="col-sm-3">Phone Number</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <input type="text" name="PhoneNumber" maxlength="20" class="form-control" value="@Model.Employee.PhoneNumber">
                        }
                        else
                        {
                            @Model.Employee.PhoneNumber
                        }
                    </dd>
                    <dt class="col-sm-3">Mobile Number</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <input type="text" name="MobileNumber" maxlength="20" class="form-control" value="@Model.Employee.MobileNumber">
                        }
                        else
                        {
                            @Model.Employee.MobileNumber
                        }
                    </dd>
                    <dt class="col-sm-3">Email</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <input type="text" name="Email" class="form-control" maxlength="255" value="@Model.Employee.Email">
                        }
                        else
                        {
                            @Model.Employee.Email
                        }
                    </dd>
                    <dt class="col-sm-3">Service</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <select class="form-control" name="ServiceId">
                                @foreach (var service in Model.AllServices)
                                {
                                    <option value="@service.Id">@service.Name</option>
                                }
                            </select>
                        }
                        else
                        {
                            @Model.Service.Name
                        }
                    </dd>
                    <dt class="col-sm-3">Site</dt>
                    <dd class="col-sm-9">
                        @if (User.IsInRole("Admin"))
                        {
                            <select class="form-control" name="SiteId" value="@Model.Employee.SiteId">
                                @foreach (var site in Model.AllSites)
                                {
                                    <option value="@site.Id">@site.Name</option>
                                }
                            </select>
                        }
                        else
                        {
                            @Model.Site.Name
                        }
                    </dd>
                    <div class="d-flex justify-content-end mb-4">
                        @if (User.IsInRole("Admin"))
                        {
                            <button asp-page-handler="UpdateEmployee" asp-route-employeeId="@Model.Employee.Id" class="btn btn-primary" type="submit">Update Employee</button>
                            <button asp-page-handler="DeleteEmployee" asp-route-employeeId="@Model.Employee.Id" type="submit" class="btn btn-danger ml-2">Delete Employee</button>
                        }
                    </div>
                </form>
            </dl>
            
        </dl>
    </div>
</div>


<script>
    var serviceId = '@Model.Employee.ServiceId';
    var selectService = document.querySelector('select[name="ServiceId"]');
    selectService.value = serviceId;
    
    var siteId = '@Model.Employee.SiteId';
    var selectSite = document.querySelector('select[name="SiteId"]');
    selectSite.value = siteId;
</script>

CesiCompanyDirectory/Pages/Services.cshtml
@page
@model CesiCompanyDirectory.Pages.Services


@{
    ViewData["Title"] = "Services Management";
}

@if (User.IsInRole("Admin"))
{
    <h1>Service</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var service in Model.AllService)
        {
            <tr>
                <td>@service.Name</td>
                <td><a asp-page="./UpdateDeleteService" asp-route-serviceId="@service.Id" class="btn btn-warning">Edit/Delete</a></td>
            </tr>
        }
        </tbody>
    </table>

    <div class="d-flex justify-content-end mb-4">
        <a asp-page="./AddService" class="btn btn-success">Add New Service</a>
    </div>
}

CesiCompanyDirectory/Pages/UpdateDeleteService.cshtml
@page
@model CesiCompanyDirectory.Pages.UpdateDeleteService

@{
    ViewData["Title"] = "Update/Delete Service";
}


@if (User.IsInRole("Admin"))
{
    <div class="container">
        <div class="row d-flex justify-content-between align-items-center mb-4">
            <dl class="col-md-9">
                <h1>Service to Update or Delete</h1>
                 @if (TempData["ErrorMessage"] != null)
                 {
                     <div class="alert alert-danger" role="alert">
                         @TempData["ErrorMessage"]
                     </div>
                 }
                <dl class="row">
                    <form method="post">
                        <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="Name" maxlength="255" class="form-control" value="@Model.Service?.Name">
                        </dd>
                        <div class="d-flex justify-content-end mb-4">
                            <button asp-page-handler="UpdateService" asp-route-serviceId="@Model.Service?.Id" class="btn btn-primary" type="submit">Update Service</button>
                            <button asp-page-handler="DeleteService" asp-route-serviceId="@Model.Service?.Id" class="btn btn-danger" type="submit">Delete Service</button>
                        </div>
                    </form>
                </dl>
            </dl>
        </div>
    </div>
}

CesiCompanyDirectory/Pages/UpdateDeleteSite.cshtml
@page
@model CesiCompanyDirectory.Pages.UpdateDeleteSite

@{
    ViewData["Title"] = "Update/Delete Site";
}


@if (User.IsInRole("Admin"))
{
    <div class="container">
        <div class="row d-flex justify-content-between align-items-center mb-4">
            <dl class="col-md-9">
                <h1>Service to Update or Delete</h1>
                 @if (TempData["ErrorMessage"] != null)
                 {
                     <div class="alert alert-danger" role="alert">
                         @TempData["ErrorMessage"]
                     </div>
                 }
                <dl class="row">
                    <form method="post">
                       <dt class="col-sm-3">Name</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="Name" maxlength="255" class="form-control" value="@Model.Site?.Name">
                        </dd>
                        <dt class="col-sm-3">City</dt>
                        <dd class="col-sm-9">
                            <input type="text" name="City" maxlength="255" class="form-control" value="@Model.Site?.City">
                        </dd>
                        <div class="d-flex justify-content-end mb-4">
                            <button asp-page-handler="UpdateSite" asp-route-siteId="@Model.Site?.Id" class="btn btn-primary" type="submit">Update Site</button>
                            <button asp-page-handler="DeleteSite" asp-route-siteId="@Model.Site?.Id" class="btn btn-danger" type="submit">Delete Site</button>
                        </div>
                    </form>
                </dl>
            </dl>
        </div>
    </div>
}